
#网站设置 详细https://github.com/mojombo/jekyll/wiki/configuration
markdown:         kramdown
highlighter:      pygments
paginate:         4
#permalink: /:year/:month/:day/:title
permalink:        /post/:title.html

title:            Hugo's Blog
url:
prod_url:         http://hugowen.com
feed:             atom.xml
author:
    name:         Hugo
    email:        hugowen20@gmail.com

follow:
    email:        hugowen20@gmail.com
    github:       https://github.com/HugoWen
    twitter:      https://www.twitter.com/hugo_wen
    google:       https://plus.google.com/107483619032085919305
    facebook:     https://facebook.com/hugo_wen
    weibo:     	  http://weibo.com/whfallen


indexContent:     true


keywords:         "hugo, hugo个人博客"
description:      "热爱开源，崇尚自由"

blogName:         Hugo's Blog
blogDesc:         <br />Shanghai, China
favicon:          favicon.ico
theme:            henter-diandian

duoshuo:           hugo

copyright:        Copyright © 2014-2015 Hugo All rights reserved.

music:            http://a.libdd.com/farm1/19/53EAEE74712880DBF40B0A7915561C13.mp3
